### ISSUE TITLE
Export menu - unexpected styling

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#12]
Export menu is displaying with unexpected colors
<img width="474" alt="sketchpad-export-menu" src="https://user-images.githubusercontent.com/48165321/90925916-e5574700-e3a6-11ea-955d-2b4ded59fead.png">

**Comment by mudcube** [comment]
@ryanreece Must be happening with the build?

**Comment by ryanreece** [comment]
Cross-posted to `sketch-api` repo: https://github.com/SketchIO/sketch-api/issues/2144

**Comment by mudcube** [comment]
Resolved in v2020.0.428 and above.  @ryanreece will push update
