### ISSUE TITLE
Download menu -> download pdf not working

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#13]
I'm able to succesfully download all file formats, except pdf's. clicking download button does not throw error message. Also, noticed buttons, on this menu appear slightly inset from their outlines
![sketchpad-download-pdf](https://user-images.githubusercontent.com/48165321/90927257-9bbc2b80-e3a9-11ea-856e-f2c38310292d.gif)

**Comment by mudcube** [comment]
@ryanreece I think this is a hosts issue, and the PDF package is not being loaded.
