### ISSUE TITLE
Pixel fill not working

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#16]
When first trying the pixel fill I was able to get preview functionality and had access to a slider. Once I pressed the "Finish Editing" button, the changes didn't take effect. When I tried to re apply the pixel fill, the slider was not present and there was no preview functionality. When pressing the "Finish Editing" button, no changes were made either. I attempted to change the fill style just to see some change but, nothing was altered.

![pixelissue mov](https://user-images.githubusercontent.com/56529123/90960451-79341c00-e456-11ea-93d0-52ea82890887.gif)

![pixelfill2 mov](https://user-images.githubusercontent.com/56529123/91073022-41141100-e5ef-11ea-8ae8-fea517c35015.gif)

Thanks,
Nate

**Comment by ryanreece** [comment]
x-posted to SketchAPI: https://github.com/SketchIO/sketch-api/issues/2145

**Comment by ryanreece** [comment]
@3t8U This issue should now be resolved on https://beta.sketchpad.app. Can you please do a hard refresh and verify that the Pixel Fill works for you?

@RyanDuff613 Can you also test the Pixel Fill tool and verify it works for you?

Please go ahead and close this issue once both of you confirm the Pixel Fill is working. Thank you!

**Comment by 3t8U** [comment]
It's working for me! @RyanDuff613 how about you?

Thanks,
Nate

**Comment by RyanDuff613** [comment]
Hi All,

Spent the last half hour or so playing with the Pixel Fill tool and it
seems to be working as expected.

-Ryan

**Comment by 3t8U** [comment]
Cool, I'll close it then :) 

Thanks @RyanDuff613 !
