### ISSUE TITLE
Move Point -> Undo does not restore path to previous state

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#28]
![movePointUndo](https://user-images.githubusercontent.com/48165321/91361320-e4f6eb80-e7ac-11ea-986d-6b79441b9963.gif)
When I move a point in a line, then Undo, the app resets the point in a new location rather than the points previous location.

**Comment by mudcube** [comment]
Resolved in latest SketchAPI
