### ISSUE TITLE
Progress not saving on refresh

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#30]
It appears all work is lost in Logomakr during a page refresh. I tested with my own images and using provided clipart. Both provided the same result.

![refresh1 mov](https://user-images.githubusercontent.com/56529123/91363717-060e0b00-e7b2-11ea-8374-a09b8c7acd78.gif)

<img width="1423" alt="Screen Shot 2020-08-26 at 3 33 51 PM" src="https://user-images.githubusercontent.com/56529123/91363528-ab74af00-e7b1-11ea-9876-46c880231ba8.png">

Thanks,
Nate

**Comment by ryanreece** [comment]
Hey @3t8U Please use https://test.logomakr.com for testing. logomakr.com is the live site and is an older version. I'll ping you when you should test https://logomakr.com.

**Comment by 3t8U** [comment]
Yep @ryanreece, that fixed it ;) 

Thanks!
Nate
