### ISSUE TITLE
Move Handle -> Undo does not restore path to previous state

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#32]
![moveHandleUndo](https://user-images.githubusercontent.com/48165321/91372073-8ab75400-e7c7-11ea-82c5-71d77b9a820a.gif)
This may be redundant as it's similar to the issue with using Undo after moving a point. If I move a handle on a curved path and then hit Undo, the path does not return to its previous state

**Comment by mudcube** [comment]
Resolved
