### ISSUE TITLE
Layer Menu Persistence

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#36]
I ran into the same issue I found in Sketchpad with selected layers in the Layers menu persisting as ghost images after closing the menu. Reopening and closing the menu doesn't remove them. They are also persisting into the project page after saving (see second image).
![layerMenuPersistence2](https://user-images.githubusercontent.com/48165321/91384892-89e0eb00-e7e4-11ea-9cf2-d060a5a56eec.gif)

<img width="1124" alt="layerMenuPersistence3" src="https://user-images.githubusercontent.com/48165321/91384778-46867c80-e7e4-11ea-8c89-1127e010449f.png">

**Comment by mudcube** [comment]
@ryanreece I believe this was resolved recently in the API. The Plot build is probably a bit older, I imagine?
