### ISSUE TITLE
UI - Confusion over purpose of text field in font selection menu

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#39]
<img width="1280" alt="fontSelectUI" src="https://user-images.githubusercontent.com/48165321/91388116-89981e00-e7eb-11ea-90b5-c995b4f9c85e.png">
I'm a little confused about the purpose of the text field in the font selection menu. Initially I assumed I could enter text there to see it previewed as I hovered my cursor over the various font options. Then I thought it might let me search the fonts by name. Neither is true so I'm unable to figure out what it's there for.

**Comment by mudcube** [comment]
Thanks for the bug report :)  Search is resolved with Ryans latest updates to the Asset Server.
