### ISSUE TITLE
Font search function not working

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#41]
The font search function is not working. I can enter text to query but, when I press enter nothing happens.
![search mov](https://user-images.githubusercontent.com/56529123/91459056-128a7600-e83b-11ea-8b4e-f5079790e57e.gif)

<img width="1433" alt="Screen Shot 2020-08-27 at 7 23 44 AM" src="https://user-images.githubusercontent.com/56529123/91458681-a9a2fe00-e83a-11ea-8a19-4c6408ce3ff6.png">

Thanks,
Nate

**Comment by mudcube** [comment]
@ryanreece It appears that PaintServer is not returning fonts when queried with a search term:  https://asset.paintserver.com/api/text/?q=open&rows=500&start=0&fl=id,type,key,title,value,preview,variants,author,tags,featured,license,defaultVariant&sort=featured+desc,popularity+asc

**Comment by mudcube** [comment]
Closing in favor of #63
