### ISSUE TITLE
Search Bar not functioning for ClipArt

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#47]
The ClipArt search function is not working. Similar issue as the Font search not working. I am able to enter text to search ClipArt but, when I press enter, nothing happens.

![search2 mov](https://user-images.githubusercontent.com/56529123/91793682-b83c3d00-ebcd-11ea-96ce-0b7284fb2003.gif)

<img width="1429" alt="Screen Shot 2020-08-31 at 9 04 07 PM" src="https://user-images.githubusercontent.com/56529123/91793691-bffbe180-ebcd-11ea-8950-ecb6e2a94e9d.png">

Thanks,
Nate

**Comment by ryanreece** [comment]
@3t8U This issue should be resolved now. Can you verify on your end please and re-open if not?
