### ISSUE TITLE
Layer Title - Rename Bug

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#53]
I have a few different layer groups that I've renamed. The one in the video was originally named "title" but Sketchpad has renamed it something else and I'm unable to rename. I've tried reloading the page but am still unable to edit the name.
![layerTitle](https://user-images.githubusercontent.com/48165321/92027442-67d0f680-ed17-11ea-8296-5a3cdc852503.gif)

**Comment by ryanreece** [comment]
@RyanDuff613 Can you check to see if this issue still happens in the latest release?
https://beta.sketchpad.app

Thank you!

**Comment by RyanDuff613** [comment]
Hi Ryan,

Did a hard reload on the file where the issue occurred and it's still
happening. For what it's worth I haven't seen this come up at any other
point.

-Ryan

**Comment by RyanDuff613** [comment]
Ran into this issue again on a new file.
<img width="582" alt="Screen Shot 2020-09-03 at 10 09 56 AM" src="https://user-images.githubusercontent.com/48165321/92145909-c193f800-edcd-11ea-90b6-1c728c01322b.png">

**Comment by RyanDuff613** [comment]
Alright, I think I got to the bottom of this one. The error only occurs if I name a layer "title". Any other text seems to work just fine.
![layerRenameTitle](https://user-images.githubusercontent.com/48165321/92147069-74b12100-edcf-11ea-8f0d-9fe3690889b1.gif)

**Comment by mudcube** [comment]
@RyanDuff613 Nice sleuthing!
