### ISSUE TITLE
Layer Menu Height Exceeds  Window

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#54]
On my screen (13in Macbook Pro), when the number of layers exceeds 18 or so, the height of the Layers menu exceeds the height of my browser window and I'm unable to access the lower layers via the scrollbar.
![layerMenuHeight](https://user-images.githubusercontent.com/48165321/92030741-563e1d80-ed1c-11ea-81fc-781ca38b1fc3.gif)

**Comment by mudcube** [comment]
Resolved in latest SketchAPI
