### ISSUE TITLE
Grouping Layers together removing some of the layers until resizing one

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#55]
When I grouped several layers together (Web font lettering), I noticed that the placement changed and several of the layers disappeared. I was able to get the layers to return after clicking on an individual layer and resizing it which, oddly brought back all of the layers?

![layer3 mov](https://user-images.githubusercontent.com/56529123/92031374-5be83300-ed1d-11ea-888f-d932ec2ad25a.gif)

Thanks,
Nate

**Comment by ryanreece** [comment]
@3t8U Thanks for the details. Can you also upload your `.sketchpad` file to this issue? To get that use the Export menu in the lefthand bar and select download .Sketchpad. GitHub may not like the `.sketchpad` format so you might need to zip it up using Finder before uploading. It'll be helpful for us if you attach the `.sketchpad` files on issues moving forward, especially if you have a nice web lettering image like you do.

Please let me know if you have any issues uploading the `.sketchpad` file. Thank you!

**Comment by 3t8U** [comment]
Got it! I'll make sure to include those as well moving forward.

 [problem-dog.sketchpad.zip](https://github.com/SketchIO/feedback/files/5165324/problem-dog.sketchpad.zip)

Thanks,
Nate

**Comment by ryanreece** [comment]
Great, thanks Nate!

**Comment by mudcube** [comment]
Closing as duplicate of SketchIO/feedback-fall-2020#62
