### ISSUE TITLE
Zoom function not working

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#57]
After I loaded up and placed three images, I was not able to use the zoom function. I used the custom facebook size on a transparent background for the base. I clicked on the zoom button multiple times and nothing happened. I tried refreshing and checked for error messages but, there were none. 

![zoom1 mov](https://user-images.githubusercontent.com/56529123/92143217-cb1b6100-edc9-11ea-9415-ad3bbfc3cd6f.gif)

[yourenotgonnalikethisclown1.sketchpad.zip](https://github.com/SketchIO/feedback/files/5170015/yourenotgonnalikethisclown1.sketchpad.zip)

Thanks,
Nate

**Comment by mudcube** [comment]
@ryanreece Resolved in the latest SketchAPI
