### ISSUE TITLE
Open File Menu - Preview Images

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#60]
Most of the file preview images display fine for me but one in every five or so seems to place the image in the corner of a white box. Haven't noticed any particular commonality between the files in which this happens but will keep paying attention and see if I can relay any additional info.
<img width="726" alt="Screen Shot 2020-09-03 at 4 11 23 PM" src="https://user-images.githubusercontent.com/48165321/92182505-b4dcc780-ee00-11ea-9f51-1e2a3903c959.png">
<img width="352" alt="Screen Shot 2020-09-03 at 4 11 37 PM" src="https://user-images.githubusercontent.com/48165321/92182523-c0c88980-ee00-11ea-90e0-ef91576d04a6.png">

**Comment by 3t8U** [comment]
I've noticed a huge difference in the image previews in Safari and in Chrome. The sizing is really off in Safari. See the below Gif. The first is the open preview in Safari and the second window in Chrome. All of the images open fine, it's just the previews.
![open1 mov](https://user-images.githubusercontent.com/56529123/92189798-705b2700-ee14-11ea-924c-63b7cd340507.gif)

Thanks,
Nate

**Comment by mudcube** [comment]
Note:  This looks like a CSS issue... need to investigate Flexbox quirks with Safari.

**Comment by mudcube** [comment]
Resolved in v2020.0.428 and above.  @ryanreece will push update
