### ISSUE TITLE
Mirror Brush line widths and sectors

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#62]
The mirror brush currently will only draw at one line width. The slider allows you to set a different width but the tool continues to use the default value. 
![mirrorBrushLineWidth](https://user-images.githubusercontent.com/48165321/92184167-5108cd80-ee05-11ea-843d-7ed6aa65b3c2.gif)
The tool will only draw in three sectors, regardless of the slider setting.
![mirrorBrushSectors](https://user-images.githubusercontent.com/48165321/92184243-80b7d580-ee05-11ea-9ee8-f92a02973aa8.gif)

**Comment by 3t8U** [comment]
@RyanDuff613  - Did you try a refresh and if so, did you get the same result? I was having the same issue with the Web Tool and when I refreshed, everything started working fine.  It was really odd. I could move the slider but, the preview wasn't even changing much less the Web tool parameters.

Thanks,
Nate

**Comment by RyanDuff613** [comment]
After reopening the file I am able to adjust the line width. I'm still
being limited to drawing in three sectors though.
