### ISSUE TITLE
Font Search not actually searching

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#63]
When searching for fonts, the search function doesn't appear to really search for fonts. I tried several letters and just turned up "No Results". Finally, when I typed the full font name in, I just get the beginning of the fonts database.

![search2 mov](https://user-images.githubusercontent.com/56529123/92187454-aeede300-ee0e-11ea-9afc-cbe858198a7b.gif)

<img width="1251" alt="Screen Shot 2020-09-03 at 5 52 56 PM" src="https://user-images.githubusercontent.com/56529123/92187467-bad9a500-ee0e-11ea-9038-66a1b9b1477d.png">

Thanks,
Nate

**Comment by mudcube** [comment]
@ryanreece PaintServer is not returning fonts when queried with a search term: https://asset.paintserver.com/api/text/?q=open&rows=500&start=0&fl=id,type,key,title,value,preview,variants,author,tags,featured,license,defaultVariant&sort=featured+desc,popularity+asc
