### ISSUE TITLE
Unable to undo work after refresh

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#64]
After refreshing Safari, I am unable to undo work made before the refresh. 

![refresh1 mov](https://user-images.githubusercontent.com/56529123/92188002-2c662300-ee10-11ea-98c9-b37e1a17aa1f.gif)

[My Drawing.sketchpad.zip](https://github.com/SketchIO/feedback/files/5172092/My.Drawing.sketchpad.zip)

<img width="993" alt="Screen Shot 2020-09-03 at 6 08 37 PM" src="https://user-images.githubusercontent.com/56529123/92188102-85ce5200-ee10-11ea-848c-b5e5ef249b19.png">

Thanks,
Nate

**Comment by mudcube** [comment]
Closing as history is session specific.  The reason for this is that if it wasn't, we'd have to upgrade history events (which would be tricky to maintain) and also it would balloon the JSON files, which would eventually cause saving issues.  Thanks for the report, but going to go ahead and close this one as a non-issue.
