### ISSUE TITLE
Zoom Function Not Working in Safari Browser

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#68]
The Zoom Function is not working. When I click on the Zoom in / out button, nothing happens. 

<img width="1438" alt="Screen Shot 2020-09-04 at 5 55 05 PM" src="https://user-images.githubusercontent.com/56529123/92293472-aa8dfc80-eed8-11ea-82e6-96d8be8d6b88.png">

![zoom5 mov](https://user-images.githubusercontent.com/56529123/92293485-d4472380-eed8-11ea-92c8-f22196800687.gif)

Thanks,
Nate

**Comment by mudcube** [comment]
Resolved in v2020.0.428 and above. @ryanreece will push update
