### ISSUE TITLE
Keyboard scroll feature request

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#72]
When I was scrolling through the ClipArt, I noticed that you cannot click on the side scroll bar to activate keyboard shortcut scrolling with the up or down arrows. After further investigation, I found that this isn't possible with any of the scrolling menus using Safari or Chrome. It's totally a preference thing and maybe not even necessary however, I would find it helpful. 

![scroll1 mov](https://user-images.githubusercontent.com/56529123/92518367-16b87b00-f1cd-11ea-8437-bc8f43500afc.gif)

Thanks,
Nate

**Comment by mudcube** [comment]
Good catch! :)
I've updated the SketchAPI so you can use arrows keys on the viewport scrollbars.
cc @ryanreece
