### ISSUE TITLE
User Guide quick links not working

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#75]
The user guide quick links are not working in Safari. In Chrome everything is working fine and I am able to navigate the user guide in its entirety. I am able to navigate to the next page with the demo from the "welcome" page. However, the demo doesn't load and I cannot go any further using the "Next" button.

<img width="1439" alt="Screen Shot 2020-09-09 at 9 42 00 AM" src="https://user-images.githubusercontent.com/56529123/92627825-c6025a00-f280-11ea-8c9d-bc067c6cdc87.png">

![user1 mov](https://user-images.githubusercontent.com/56529123/92628171-41fca200-f281-11ea-87c5-fd982143d23d.gif)

Thanks,
Nate

**Comment by mudcube** [comment]
@ryanreece This seems to be working for me, what about you?

**Comment by mudcube** [comment]
No longer seems to be an issue.
