### ISSUE TITLE
Radial Fill Outline function not working on some tools

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#76]
The following tools will not allow a Radial Fill in the Outline : 

- [ ] Pen
- [ ] Sketchy
- [ ] Calligraphy
- [ ] Streamer
- [ ] Crayon
- [ ] Spray Paint 
- [ ] Fur
- [ ] Web
- [ ] Spirograph 

When I try to access the radial fill option, the icon is lightened and the button does not respond. I tested this in both Chrome & Safari.
![radial1 mov](https://user-images.githubusercontent.com/56529123/92645437-b2afb880-f299-11ea-90c5-faf859b72d14.gif)

<img width="1176" alt="Screen Shot 2020-09-09 at 12 46 14 PM" src="https://user-images.githubusercontent.com/56529123/92645933-80528b00-f29a-11ea-9f89-3be45b564c7f.png">

<img width="1440" alt="Screen Shot 2020-09-09 at 12 47 32 PM" src="https://user-images.githubusercontent.com/56529123/92646055-b42db080-f29a-11ea-8304-d5d59283caf8.png">

Also - It's probably worth noting that SketchPad is running suuuuper slow in Safari and even having trouble loading fully as where it still loads up fine in Chrome.

Thanks,
Nate

**Comment by mudcube** [comment]
Thanks for the bug report!  This is actually by design, those tools cycle through the gradient colors, so radialGradient cannot technically be supported.  With than in mind, how would you imagine the interface to look so that felt more natural to you? cc @ryanreece

**Comment by 3t8U** [comment]
The most intuitive interface for me would be just to eliminate the radial option from the interface when it doesn't apply. Keep in mind that, this is coming from someone who isn't familiar with Photoshop or Illustrator ( Feel free to imagine me trying to use a skill saw to to open a letter just because it's sharp as an analogy ). Maybe the options would change for each tool and the buttons could realign? I would have it look something like this.

<img width="640" alt="3OptionInterface" src="https://user-images.githubusercontent.com/56529123/93610903-7d365980-f982-11ea-80e1-20b504065387.png">


Thanks,
Nate

**Comment by mudcube** [comment]
Thanks for the advice! 
Implemented in the latest SketchAPI :)
cc @ryanreece
