### ISSUE TITLE
Pen & Streamer tools have two adjustment controls on a single slider

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#77]
The Pen & Streamer tool seem to have two independent functioning controls on one slider. I came across this issue both in Chrome and in Safari. There are two control dots and two corresponding size boxes that work completely. They seem to be dueling for the love of the single line....

<img width="340" alt="Screen Shot 2020-09-10 at 6 42 24 AM" src="https://user-images.githubusercontent.com/56529123/92738448-cbb77880-f330-11ea-8f35-1bdebe4279fa.png">

![width2 mov](https://user-images.githubusercontent.com/56529123/92739571-e2aa9a80-f331-11ea-81c7-9e693acf7286.gif)

Thanks,
Nate

**Comment by mudcube** [comment]
This is actually a non-issue—the two sliders are for the MIN/MAX parameters of the Pen/Streamer tools.  It's a lot more obvious to see this when you're actually using the tool, when you speed up the line gets closer to the MIN, and when you slow down it gets closer to the MAX.

**Comment by 3t8U** [comment]
Whoops! Sorry about that, I was just drawing straight lines before when
testing and not seeing any change. I didn't even think to try different
speeds in my strokes.

Thanks,
Nate

**Comment by mudcube** [comment]
No problemo!  Thanks for the bug report, I imagine other people think the same thing as well.  Eventually we're going to be deprecating the Pen/Streamer for an upgraded TileBrush though, so going to make a mental note that the controls are slightly confusing, and at that time, will try to make the new brushes more intuitive.  :)
