### ISSUE TITLE
Tile Brush Parameters not changing / reseting

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#8]
I noticed that when attempting to change parameters on the tile brush after setting initial ones, none of the changes seem to have effect. When switching to a different tool, the parameters can change for the new tool with no issue once. When switching back to the tile brush however, the parameters are the same as they were beforehand and do not change and vice versa. It seems that you can only change the tile once and then it locks the tool into those parameters. I'm gonna keep digging into this issue to try and get a more succinct diagnosis. I feel like there is a root issue here that I am missing.

![tilebrush_patternissue mov](https://user-images.githubusercontent.com/56529123/90908819-bd0d1f80-e389-11ea-99c2-10a695e1019c.gif)
![tilebrush_patternissue2 mov](https://user-images.githubusercontent.com/56529123/90908829-c26a6a00-e389-11ea-945e-7950c470a5ed.gif)

Thanks,
Nate

**Comment by ryanreece** [comment]
Seems to be working locally, need to verify again

**Comment by ryanreece** [comment]
@3t8U Can you verify that this issue no longer happens for you? If it doesn't happen anymore, please go ahead and close this one. Thanks!!

**Comment by 3t8U** [comment]
Works now!
