### ISSUE TITLE
Crop Tool > Constrain Proportions not working properly after selecting template size

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#80]
After applying one of the provided template sizes to my file and then clicking the lock to constrain proportions, the tool does not correctly constrain when I attempt to resize. In the gif you'll see that I select 800x600, apply the change and then click the lock. When I input 400 into the height field I expect the width to be 300 but instead get 3000. I've been able to replicate the same error in Firefox, Safari and Chrome.
![cropping](https://user-images.githubusercontent.com/48165321/92970132-03a6e480-f433-11ea-8cc6-f04b17b1f882.gif)

**Comment by mudcube** [comment]
Thanks for the bug report! :)
Sorted out in the latest SketchAPI
cc @ryanreece
