### ISSUE TITLE
Layer Grouping causing elements to be hidden

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#81]
Not sure if this is just a temporary issue but Sketchpad is currently hiding elements when I attempt to group them. The behavior is the same across browsers. If I toggle invisibility, the elements in the group display momentarily but quickly revert to being hidden. 
![layerGroupingCausesDisappearance](https://user-images.githubusercontent.com/48165321/93402882-cda29f80-f83a-11ea-8b76-593e9b6caa00.gif)

**Comment by mudcube** [comment]
Closing as duplicate of #55
