### ISSUE TITLE
Layer Lock Icon is missing

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#82]
Most likely a temporary development issue but wanted to point out that the Lock currently are not visible. Chrome and Safari display an empty space where the lock would normally be located. Firefox displays a small square containing the text E934. I'm still able to lock/unlock the layers by clicking in the area where the lock should be.
<img width="372" alt="Screen Shot 2020-09-16 at 9 11 21 PM" src="https://user-images.githubusercontent.com/48165321/93419547-f7bb8800-f861-11ea-92c6-5263b972c80d.png">
<img width="345" alt="Screen Shot 2020-09-16 at 9 11 41 PM" src="https://user-images.githubusercontent.com/48165321/93419549-f8541e80-f861-11ea-9343-3b2e371dd6a9.png">

**Comment by mudcube** [comment]
Appears to be resolved in the latest release on sketchpad.dev
