### ISSUE TITLE
Shape Tools > Burst tool sometimes producing a circle

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#87]
The Burst Tool unpredictably produces circles. I can usually adjust the Slide/Slope parameters to produce a burst but it jumps between bursts and circles without control. Issue occurs across browsers.

![burstTool](https://user-images.githubusercontent.com/48165321/93537455-5f281500-f900-11ea-898c-380cae519f3d.gif)

**Comment by mudcube** [comment]
Thanks, we'd probably never of found this one.  It's well hidden.  Easy to fix though!
cc @ryanreece
