### ISSUE TITLE
Text Tool in Firefox

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#88]
When using Sketchpad in Firefox, the text tool will not allow me to edit text either upon creating the element or after selecting it.

![firefoxText](https://user-images.githubusercontent.com/48165321/93541742-1aa27680-f90c-11ea-93c1-c125ee9d4a70.gif)

**Comment by mudcube** [comment]
Oh nos!  That's a show stopper.  Thanks for the great bug report :)
Sorted in latest SketchAPI
cc @ryanreece
