### ISSUE TITLE
Font menu prevents scolling through entire menu

### ISSUE THREAD

**Issue by RyanDuff613** [SketchIO/feedback-summer-2020#90]
Currently, the font selection menu will only allow me to scroll a short way through the menu before returning to the currently selected font. In the video I first attempt to scroll using the scroll wheel on my mouse, then attempt to use the scroll bar in the browser window, both return to the selected font. The scroll wheel behavior is consistent across browsers. The scroll bar is only an issue in Firefox
![fontScroll](https://user-images.githubusercontent.com/48165321/93646071-4ed47080-f9ba-11ea-9c05-c4cac97625b6.gif)

**Comment by mudcube** [comment]
Woopsiedaisy, my bad.  Sorted in the latest SketchAPI
cc @ryanreece
