### ISSUE TITLE
Proportions not resetting using Windows 8

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#95]
For a good time, try testing on an old Windows machine.... ;) 
![image](https://user-images.githubusercontent.com/56529123/93685844-e68f9880-fa66-11ea-81b7-9719b7fdd00f.png)
On the preceding set up using Chrome, I noticed when canceling the crop tool after applying a crop, the proportions on the crop tool are not resetting.

![prop1 mov](https://user-images.githubusercontent.com/56529123/93686170-54d55a80-fa69-11ea-9707-baf1a69cad19.gif)

![image](https://user-images.githubusercontent.com/56529123/93685988-260ab480-fa68-11ea-88a0-00d8d99552d6.png)

Nate

**Comment by mudcube** [comment]
Good point! Resets back to the original values in the latest SketchAPI.
cc'ing @ryanreece to build & release
