### ISSUE TITLE
Mirrored Repeat function doesn't seem to be working

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#96]
When using the Tile Brush in Windows and Chrome, I couldn't seem to get the "Mirrored Repeat" setting on the Tile Brush to produce a different output from the "Repeat" setting. It is possible I don't quite understand what it is supposed to do and I don't see any difference in the strokes. I tried several different patterns and widths on my Windows machine and my Mac both using Chrome. 

<img width="1440" alt="Screen Shot 2020-09-20 at 8 32 01 PM" src="https://user-images.githubusercontent.com/56529123/93731114-7e34da00-fb80-11ea-8f21-c0099bb6bbff.png">

<img width="1426" alt="Screen Shot 2020-09-20 at 8 27 10 PM" src="https://user-images.githubusercontent.com/56529123/93731061-46c62d80-fb80-11ea-9f37-9f612b284f3d.png">

Thanks,
Nate

**Comment by mudcube** [comment]
Thanks for the bug report!  Yup, it was broken.  But also, probably not the easiest to understand interface.  In the latest SketchAPI there are icons to show what the Tile Modes do:

<img width="522" alt="Screen Shot 2020-09-21 at 1 02 37 AM" src="https://user-images.githubusercontent.com/101564/93744115-25783800-fba6-11ea-9cb2-d9110267921c.png">

cc @ryanreece
