### ISSUE TITLE
Controls hanging up in Windows 8 / Chrome

### ISSUE THREAD

**Issue by 3t8U** [SketchIO/feedback-summer-2020#97]
I am finding that many of the controls and parameters in the side bar are hanging up and not affecting the corresponding tools properly until I refresh the page. For example, using the sketchy tool and zero-ing out the outline teardrop in the control panel won't mute the outline or trying to change the line width if the eraser will not work unless I do a page refresh. I suppose it could be this ancient computer I'm using but, I'm not positive. I am working on setting up a virtual machine tonight and hope to have it set up by tomorrow to test this problem further and isolate if it's my machine or a windows 8 hang up. The console is giving me a "Failed to load resource: server responded with a status of 404" message. I'll keep y'all posted. I'll still be testing throughout the week and I want to get to the bottom of this.

Thanks,
Nate

PS - sorry for the lack of Gifs / Screenshots on this one. I'm looking for a better workflow to get these things off of this old windows machine besides VLC screen captures  moved via usb and screenshots 😬

**Comment by mudcube** [comment]
Thanks for the bug report!  Resolved in the latest SketchAPI :)
cc'ing @ryanreece to build & release
